[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "styles", "index.html"]
ignore = ["dist", "target"]

[serve]
port = 3000
address = "127.0.0.1"
protocol = "http"
open = false

[clean]
dist = "dist"
cargo = true
